name: Secret from KeyVault
on: [push]
jobs:
  RetrieveKeyVaultSecrets:
    runs-on: ubuntu-latest
    steps:  
    - uses: Azure/login@v2.1.0
      with:
        auth-type: IDENTITY
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: Azure/get-keyvault-secrets@v1
      with: 
        keyvault: ${{ secrets.KEYVAULT_NAME }}
        secrets: 'GitHubSecret'
        # keyVault: 'ccdl-eastus2-web-app-kv'
        # secrets: 'ccdl-subc-id'
      id: mySecrets
    - name: Read secret from Azure Key Vault
      run: echo "The secret value is ${{ steps.mySecrets.outputs.GitHubSecret }}"
