name: Secret from KeyVault
on: 
  push: 
    branches: [main]
  # workflow_dispatch
env:
  SECRETVALUE: ''

jobs:
  retrieveWithAction:
    runs-on: ubuntu-latest
    steps:  
    - uses: Azure/login@v2.1.0
      with:
        creds: ${{ secrets.azurecredentials }}
    - uses: Azure/get-keyvault-secrets@v1
      with: 
        keyvault: 'GitHubKeyVault'
        secrets: 'GitHubSecret'
      id: mySecrets
