name: Retrieve secret from Azure Key Vault
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  retrieve-secret:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Azure
      uses: azure/login@v2.1.0
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}

    - name: Retrieve secret from Azure Key Vault
      id: retrieve-secret
      uses: azure/secrets@v1.0.16
      with:
        keyvault: ${{ secrets.AZURE_KEY_VAULT }}
        secrets: |
          MY_SECRET

    - name: Use the secret
      run: |
        echo "Secret retrieved: ${{ steps.retrieve-secret.outputs.MY_SECRET }}"
